language: cpp
compiler: clang
sudo: required

git:
  submodules: false 
  #http://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci/24600210#24600210

before_install:
  - chmod +rx tools/travis/before_install.sh
  - ./tools/travis/before_install.sh

install:
  - chmod +rx tools/travis/install.sh 
  - ./tools/travis/install.sh 

before_script:
  - chmod +rx tools/travis/before_script.sh 
  - ./tools/travis/before_script.sh 

script:
  - chmod +rx tools/travis/script.sh 
  - ./tools/travis/script.sh 