language: cpp
compiler: clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-multilib
  - wget -qO- https://deb.nodesource.com/setup_0.12 | sudo bash -
  - sudo apt-get install -y nodejs

install:
  - wget http://www.sourcemod.net/smdrop/1.8/sourcemod-1.8.0-git5506-linux.tar.gz -O /tmp/sourcemod.tar.gz
  - tar -xzvf /tmp/sourcemod.tar.gz
  - chmod +rx tools/npm_dependencies.sh
  - ./tools/npm_dependencies.sh
  
before_script:
  - chmod +rx addons/sourcemod/scripting/spcomp
  - chmod +rx addons/sourcemod/scripting/compile.sh
  - chmod +rx tools/travis_build.sh
  
script:
  - ./tools/travis_build.sh